import type { CustomerAccount, DeliveryAgent, Order, Product, PromoCode } from "@/lib/types";
import { buildWeightVariantPrices, WEIGHT_UNIT_OPTIONS } from "@/lib/units";

export const initialProducts: Product[] = [
  {
    id: "p-101",
    name: "Mustard Oil",
    category: "grocery",
    price: 155,
    image_url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80",
    description: "Strong, aromatic mustard oil for everyday Bengali cooking.",
    stock: 40,
    brand: "Oils & Spices",
    dietary: ["cold-pressed"],
    unitType: "package",
    unitOptions: ["1 Liter", "2 Liter", "5 Liter"],
    variantPrices: { "1 Liter": 155, "2 Liter": 300, "5 Liter": 730 },
    reviews: []
  },
  {
    id: "p-102",
    name: "Sunflower Oil",
    category: "grocery",
    price: 145,
    image_url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80",
    description: "Light refined sunflower oil for frying and daily cooking.",
    stock: 38,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Liter", "2 Liter", "5 Liter"],
    variantPrices: { "1 Liter": 145, "2 Liter": 280, "5 Liter": 680 },
    reviews: []
  },
  {
    id: "p-103",
    name: "Turmeric Powder",
    category: "grocery",
    price: 9,
    image_url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=800&q=80",
    description: "Bright turmeric powder for curries, vegetables, and marinades.",
    stock: 75,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(9),
    reviews: []
  },
  {
    id: "p-104",
    name: "Red Chili Powder",
    category: "grocery",
    price: 10,
    image_url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
    description: "Hot red chili powder for spicy home cooking.",
    stock: 70,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(10),
    reviews: []
  },
  {
    id: "p-105",
    name: "Garam Masala",
    category: "grocery",
    price: 28,
    image_url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
    description: "Aromatic garam masala blend for rich Indian dishes.",
    stock: 55,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(28),
    reviews: []
  },
  {
    id: "p-106",
    name: "Cumin Seeds",
    category: "grocery",
    price: 12,
    image_url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
    description: "Whole cumin seeds for tempering and spice mixes.",
    stock: 60,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(12),
    reviews: []
  },
  {
    id: "p-107",
    name: "Black Pepper",
    category: "grocery",
    price: 38,
    image_url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
    description: "Sharp black pepper for seasoning and spice blends.",
    stock: 42,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(38),
    reviews: []
  },
  {
    id: "p-108",
    name: "Salt",
    category: "grocery",
    price: 1,
    image_url: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=800&q=80",
    description: "Everyday iodized salt for cooking.",
    stock: 120,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(1),
    reviews: []
  },
  {
    id: "p-109",
    name: "Sugar",
    category: "grocery",
    price: 2,
    image_url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
    description: "Clean white sugar for tea, sweets, and baking.",
    stock: 110,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(2),
    reviews: []
  },
  {
    id: "p-110",
    name: "Frozen Peas",
    category: "grocery",
    price: 95,
    image_url: "https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?auto=format&fit=crop&w=800&q=80",
    description: "Frozen green peas packed for quick cooking.",
    stock: 35,
    brand: "Frozen Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 95, "2 Packets": 180 },
    reviews: []
  },
  {
    id: "p-111",
    name: "Frozen Corn",
    category: "grocery",
    price: 90,
    image_url: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=800&q=80",
    description: "Sweet frozen corn kernels for snacks and recipes.",
    stock: 32,
    brand: "Frozen Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 90, "2 Packets": 170 },
    reviews: []
  },
  {
    id: "p-112",
    name: "Shampoo",
    category: "grocery",
    price: 160,
    image_url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    description: "Daily-use shampoo bottle for clean hair care.",
    stock: 28,
    brand: "Personal Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 160, "2 Bottles": 310 },
    reviews: []
  },
  {
    id: "p-113",
    name: "Soap",
    category: "grocery",
    price: 35,
    image_url: "https://images.unsplash.com/photo-1607006483224-7b17f9f5b2b2?auto=format&fit=crop&w=800&q=80",
    description: "Bathing soap for everyday personal care.",
    stock: 90,
    brand: "Personal Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Piece", "4 Pieces"],
    variantPrices: { "1 Piece": 35, "4 Pieces": 130 },
    reviews: []
  },
  {
    id: "p-114",
    name: "Toothpaste",
    category: "grocery",
    price: 85,
    image_url: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=800&q=80",
    description: "Family toothpaste tube for daily dental care.",
    stock: 48,
    brand: "Personal Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Tube", "2 Tubes"],
    variantPrices: { "1 Tube": 85, "2 Tubes": 160 },
    reviews: []
  },
  {
    id: "p-115",
    name: "Hair Oil",
    category: "grocery",
    price: 120,
    image_url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    description: "Nourishing hair oil bottle for regular use.",
    stock: 34,
    brand: "Personal Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 120, "2 Bottles": 230 },
    reviews: []
  },
  {
    id: "p-116",
    name: "Detergent Powder",
    category: "grocery",
    price: 110,
    image_url: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=800&q=80",
    description: "Detergent powder packet for clean clothes.",
    stock: 52,
    brand: "Household",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 110, "2 Packets": 210 },
    reviews: []
  },
  {
    id: "p-117",
    name: "Dishwash Liquid",
    category: "grocery",
    price: 95,
    image_url: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=800&q=80",
    description: "Dishwash liquid bottle for utensils and kitchen cleaning.",
    stock: 44,
    brand: "Household",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 95, "2 Bottles": 180 },
    reviews: []
  },
  {
    id: "p-118",
    name: "Garbage Bags",
    category: "grocery",
    price: 75,
    image_url: "https://images.unsplash.com/photo-1604187351574-c75ca79f5807?auto=format&fit=crop&w=800&q=80",
    description: "Garbage bag packet for daily home waste disposal.",
    stock: 50,
    brand: "Household",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 75, "2 Packets": 140 },
    reviews: []
  },
  {
    id: "p-119",
    name: "Baby Diapers",
    category: "grocery",
    price: 320,
    image_url: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
    description: "Baby diaper packet for comfortable daily protection.",
    stock: 24,
    brand: "Baby Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 320, "2 Packets": 620 },
    reviews: []
  },
  {
    id: "p-120",
    name: "Baby Wipes",
    category: "grocery",
    price: 95,
    image_url: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
    description: "Soft baby wipes packet for gentle cleaning.",
    stock: 38,
    brand: "Baby Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 95, "2 Packets": 180 },
    reviews: []
  },
  {
    id: "p-121",
    name: "Baby Lotion",
    category: "grocery",
    price: 150,
    image_url: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
    description: "Baby lotion bottle for soft skin care.",
    stock: 26,
    brand: "Baby Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 150, "2 Bottles": 290 },
    reviews: []
  },
  {
    id: "p-122",
    name: "Pet Shampoo",
    category: "grocery",
    price: 180,
    image_url: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=800&q=80",
    description: "Pet shampoo bottle for gentle coat cleaning.",
    stock: 18,
    brand: "Pet Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 180, "2 Bottles": 345 },
    reviews: []
  },
  {
    id: "p-123",
    name: "Instant Noodles",
    category: "grocery",
    price: 18,
    image_url: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80",
    description: "Quick instant noodles packet for snacks and meals.",
    stock: 140,
    brand: "Instant Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "6 Packets", "12 Packets"],
    variantPrices: { "1 Packet": 18, "6 Packets": 105, "12 Packets": 200 },
    reviews: []
  },
  {
    id: "p-124",
    name: "Pasta",
    category: "grocery",
    price: 65,
    image_url: "https://images.unsplash.com/photo-1551462147-37885acc36f1?auto=format&fit=crop&w=800&q=80",
    description: "Pasta packet for quick homemade meals.",
    stock: 58,
    brand: "Instant Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 65, "2 Packets": 125 },
    reviews: []
  },
  {
    id: "p-125",
    name: "Macaroni",
    category: "grocery",
    price: 60,
    image_url: "https://images.unsplash.com/photo-1551462147-37885acc36f1?auto=format&fit=crop&w=800&q=80",
    description: "Macaroni packet for snacks, salads, and pasta dishes.",
    stock: 54,
    brand: "Instant Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 60, "2 Packets": 115 },
    reviews: []
  },
  {
    id: "p-126",
    name: "Soup Mix",
    category: "grocery",
    price: 45,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    description: "Ready soup mix packet for warm evening snacks.",
    stock: 62,
    brand: "Instant Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "4 Packets"],
    variantPrices: { "1 Packet": 45, "4 Packets": 170 },
    reviews: []
  },
  {
    id: "p-127",
    name: "Eggs",
    category: "grocery",
    price: 78,
    image_url: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=800&q=80",
    description: "Fresh eggs sold by dozen.",
    stock: 60,
    brand: "Meat & Seafood",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Dozen", "2 Dozen"],
    variantPrices: { "1 Dozen": 78, "2 Dozen": 150 },
    reviews: []
  }
];

export const initialOrders: Order[] = [
  {
    order_id: "ORD-2401",
    customer_name: "Mita Roy",
    customer_phone: "9876543210",
    delivery_address: {
      id: "addr-mita",
      label: "Home",
      receiverName: "Mita Roy",
      phone: "9876543210",
      line1: "12 Station Road",
      line2: "Flat 2B",
      city: "Kolkata",
      state: "West Bengal",
      pincode: "700001",
      landmark: "Near market gate",
      distanceKm: 0.8,
      latitude: 22.5744,
      longitude: 88.3629
    },
    items_ordered: "Mustard Oil (1 Liter) x 1, Turmeric Powder (100 Gram) x 1, Salt (1 Kg) x 1",
    total_amount: 212,
    subtotal: 212,
    discount_amount: 0,
    payment_method: "UPI",
    payment_status: "Paid",
    delivery_fee: 0,
    delivery_distance: 0.8,
    status: "Preparing",
    assigned_agent_id: "agent-1",
    delivery_eta: "25 minutes",
    refund_status: "Not requested",
    invoice_number: "INV-2401",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString()
  },
  {
    order_id: "ORD-2402",
    customer_name: "Rahul Das",
    customer_phone: "9123456780",
    delivery_address: {
      id: "addr-rahul",
      label: "Work",
      receiverName: "Rahul Das",
      phone: "9123456780",
      line1: "48 College Street",
      line2: "Shop floor",
      city: "Kolkata",
      state: "West Bengal",
      pincode: "700073",
      landmark: "Book lane",
      distanceKm: 1.4,
      latitude: 22.5762,
      longitude: 88.3645
    },
    items_ordered: "Instant Noodles (6 Packets) x 1, Soap (4 Pieces) x 1, Toothpaste (1 Tube) x 1",
    total_amount: 340,
    subtotal: 320,
    discount_amount: 0,
    payment_method: "COD",
    payment_status: "Pending",
    delivery_fee: 20,
    delivery_distance: 1.4,
    status: "Pending",
    assigned_agent_id: undefined,
    delivery_eta: "Waiting for owner confirmation",
    refund_status: "Not requested",
    invoice_number: "INV-2402",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString()
  }
];

export const deliveryAgents: DeliveryAgent[] = [
  {
    id: "agent-1",
    name: "Suman Pal",
    phone: "9000011111",
    active: true
  },
  {
    id: "agent-2",
    name: "Arif Khan",
    phone: "9000022222",
    active: true
  }
];

export const promoCodes: PromoCode[] = [
  {
    code: "TAPAS10",
    type: "percentage",
    value: 10,
    minCartTotal: 200,
    description: "10% off orders above ₹200",
    active: true
  },
  {
    code: "LOCAL50",
    type: "flat",
    value: 50,
    minCartTotal: 500,
    description: "₹50 off weekly grocery baskets",
    active: true
  }
];

export const defaultCustomer: CustomerAccount = {
  id: "cus-default",
  name: "Customer",
  phone: "",
  isBlocked: false,
  addresses: [],
  orderIds: [],
  favoriteProductIds: []
};
