import type { CustomerAccount, DeliveryAgent, Order, Product, PromoCode } from "@/lib/types";
import { buildWeightVariantPrices, WEIGHT_UNIT_OPTIONS } from "@/lib/units";

const PRODUCT_IMAGE_PLACEHOLDER = "/product-photos/mustard-oil.jpg";

const coreProducts: Product[] = [
  {
    id: "p-101",
    name: "Mustard Oil",
    category: "grocery",
    price: 155,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Strong, aromatic mustard oil for everyday Bengali cooking.",
    stock: 40,
    brand: "Oils & Spices",
    dietary: ["cold-pressed"],
    unitType: "package",
    unitOptions: ["1 Liter", "2 Liter", "5 Liter"],
    variantPrices: { "1 Liter": 155, "2 Liter": 300, "5 Liter": 730 },
    reviews: []
  },
  {
    id: "p-102",
    name: "Sunflower Oil",
    category: "grocery",
    price: 145,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Light refined sunflower oil for frying and daily cooking.",
    stock: 38,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Liter", "2 Liter", "5 Liter"],
    variantPrices: { "1 Liter": 145, "2 Liter": 280, "5 Liter": 680 },
    reviews: []
  },
  {
    id: "p-103",
    name: "Turmeric Powder",
    category: "grocery",
    price: 9,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Bright turmeric powder for curries, vegetables, and marinades.",
    stock: 75,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(9),
    reviews: []
  },
  {
    id: "p-104",
    name: "Red Chili Powder",
    category: "grocery",
    price: 10,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Hot red chili powder for spicy home cooking.",
    stock: 70,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(10),
    reviews: []
  },
  {
    id: "p-105",
    name: "Garam Masala",
    category: "grocery",
    price: 28,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Aromatic garam masala blend for rich Indian dishes.",
    stock: 55,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(28),
    reviews: []
  },
  {
    id: "p-106",
    name: "Cumin Seeds",
    category: "grocery",
    price: 12,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Whole cumin seeds for tempering and spice mixes.",
    stock: 60,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(12),
    reviews: []
  },
  {
    id: "p-107",
    name: "Black Pepper",
    category: "grocery",
    price: 38,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Sharp black pepper for seasoning and spice blends.",
    stock: 42,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(38),
    reviews: []
  },
  {
    id: "p-108",
    name: "Salt",
    category: "grocery",
    price: 1,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Everyday iodized salt for cooking.",
    stock: 120,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(1),
    reviews: []
  },
  {
    id: "p-109",
    name: "Sugar",
    category: "grocery",
    price: 2,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Clean white sugar for tea, sweets, and baking.",
    stock: 110,
    brand: "Oils & Spices",
    dietary: [],
    unitType: "weight",
    unitOptions: WEIGHT_UNIT_OPTIONS,
    variantPrices: buildWeightVariantPrices(2),
    reviews: []
  },
  {
    id: "p-110",
    name: "Frozen Peas",
    category: "grocery",
    price: 95,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Frozen green peas packed for quick cooking.",
    stock: 35,
    brand: "Frozen Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 95, "2 Packets": 180 },
    reviews: []
  },
  {
    id: "p-111",
    name: "Frozen Corn",
    category: "grocery",
    price: 90,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Sweet frozen corn kernels for snacks and recipes.",
    stock: 32,
    brand: "Frozen Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 90, "2 Packets": 170 },
    reviews: []
  },
  {
    id: "p-112",
    name: "Shampoo",
    category: "grocery",
    price: 160,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Daily-use shampoo bottle for clean hair care.",
    stock: 28,
    brand: "Personal Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 160, "2 Bottles": 310 },
    reviews: []
  },
  {
    id: "p-113",
    name: "Soap",
    category: "grocery",
    price: 35,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Bathing soap for everyday personal care.",
    stock: 90,
    brand: "Personal Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Piece", "4 Pieces"],
    variantPrices: { "1 Piece": 35, "4 Pieces": 130 },
    reviews: []
  },
  {
    id: "p-114",
    name: "Toothpaste",
    category: "grocery",
    price: 85,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Family toothpaste tube for daily dental care.",
    stock: 48,
    brand: "Personal Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Tube", "2 Tubes"],
    variantPrices: { "1 Tube": 85, "2 Tubes": 160 },
    reviews: []
  },
  {
    id: "p-115",
    name: "Hair Oil",
    category: "grocery",
    price: 120,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Nourishing hair oil bottle for regular use.",
    stock: 34,
    brand: "Personal Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 120, "2 Bottles": 230 },
    reviews: []
  },
  {
    id: "p-116",
    name: "Detergent Powder",
    category: "grocery",
    price: 110,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Detergent powder packet for clean clothes.",
    stock: 52,
    brand: "Household",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 110, "2 Packets": 210 },
    reviews: []
  },
  {
    id: "p-117",
    name: "Dishwash Liquid",
    category: "grocery",
    price: 95,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Dishwash liquid bottle for utensils and kitchen cleaning.",
    stock: 44,
    brand: "Household",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 95, "2 Bottles": 180 },
    reviews: []
  },
  {
    id: "p-118",
    name: "Garbage Bags",
    category: "grocery",
    price: 75,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Garbage bag packet for daily home waste disposal.",
    stock: 50,
    brand: "Household",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 75, "2 Packets": 140 },
    reviews: []
  },
  {
    id: "p-119",
    name: "Baby Diapers",
    category: "grocery",
    price: 320,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Baby diaper packet for comfortable daily protection.",
    stock: 24,
    brand: "Baby Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 320, "2 Packets": 620 },
    reviews: []
  },
  {
    id: "p-120",
    name: "Baby Wipes",
    category: "grocery",
    price: 95,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Soft baby wipes packet for gentle cleaning.",
    stock: 38,
    brand: "Baby Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 95, "2 Packets": 180 },
    reviews: []
  },
  {
    id: "p-121",
    name: "Baby Lotion",
    category: "grocery",
    price: 150,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Baby lotion bottle for soft skin care.",
    stock: 26,
    brand: "Baby Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 150, "2 Bottles": 290 },
    reviews: []
  },
  {
    id: "p-122",
    name: "Pet Shampoo",
    category: "grocery",
    price: 180,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Pet shampoo bottle for gentle coat cleaning.",
    stock: 18,
    brand: "Pet Care",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Bottle", "2 Bottles"],
    variantPrices: { "1 Bottle": 180, "2 Bottles": 345 },
    reviews: []
  },
  {
    id: "p-123",
    name: "Instant Noodles",
    category: "grocery",
    price: 18,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Quick instant noodles packet for snacks and meals.",
    stock: 140,
    brand: "Instant Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "6 Packets", "12 Packets"],
    variantPrices: { "1 Packet": 18, "6 Packets": 105, "12 Packets": 200 },
    reviews: []
  },
  {
    id: "p-124",
    name: "Pasta",
    category: "grocery",
    price: 65,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Pasta packet for quick homemade meals.",
    stock: 58,
    brand: "Instant Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 65, "2 Packets": 125 },
    reviews: []
  },
  {
    id: "p-125",
    name: "Macaroni",
    category: "grocery",
    price: 60,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Macaroni packet for snacks, salads, and pasta dishes.",
    stock: 54,
    brand: "Instant Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "2 Packets"],
    variantPrices: { "1 Packet": 60, "2 Packets": 115 },
    reviews: []
  },
  {
    id: "p-126",
    name: "Soup Mix",
    category: "grocery",
    price: 45,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Ready soup mix packet for warm evening snacks.",
    stock: 62,
    brand: "Instant Foods",
    dietary: [],
    unitType: "package",
    unitOptions: ["1 Packet", "4 Packets"],
    variantPrices: { "1 Packet": 45, "4 Packets": 170 },
    reviews: []
  },
  {
    id: "p-127",
    name: "Eggs",
    category: "grocery",
    price: 78,
    image_url: PRODUCT_IMAGE_PLACEHOLDER,
    description: "Fresh eggs sold by single-piece quantity.",
    stock: 60,
    brand: "Meat & Seafood",
    dietary: [],
    unitType: "package",
    unitOptions: ["1", "2", "3", "4", "5", "6"],
    variantPrices: { "1": 7, "2": 14, "3": 21, "4": 28, "5": 35, "6": 42 },
    reviews: []
  }
];

const additionalProductSeeds: Array<{
  name: string;
  brand: string;
  price: number;
  stock: number;
  unitOptions?: string[];
  variantPrices?: Record<string, number>;
  dietary?: string[];
}> = [
  { name: "Basmati Rice", brand: "Rice & Staples", price: 155, stock: 70, unitOptions: ["1 Kg", "5 Kg", "10 Kg"], variantPrices: { "1 Kg": 155, "5 Kg": 740, "10 Kg": 1450 } },
  { name: "Gobindobhog Rice", brand: "Rice & Staples", price: 125, stock: 64, unitOptions: ["1 Kg", "5 Kg", "10 Kg"], variantPrices: { "1 Kg": 125, "5 Kg": 600, "10 Kg": 1180 } },
  { name: "Miniket Rice", brand: "Rice & Staples", price: 72, stock: 90, unitOptions: ["1 Kg", "5 Kg", "10 Kg"], variantPrices: { "1 Kg": 72, "5 Kg": 350, "10 Kg": 690 } },
  { name: "Sona Masoori Rice", brand: "Rice & Staples", price: 68, stock: 85, unitOptions: ["1 Kg", "5 Kg", "10 Kg"], variantPrices: { "1 Kg": 68, "5 Kg": 330, "10 Kg": 650 } },
  { name: "Parboiled Rice", brand: "Rice & Staples", price: 54, stock: 120, unitOptions: ["1 Kg", "5 Kg", "10 Kg"], variantPrices: { "1 Kg": 54, "5 Kg": 260, "10 Kg": 510 } },
  { name: "Broken Rice", brand: "Rice & Staples", price: 38, stock: 60, unitOptions: ["1 Kg", "5 Kg"], variantPrices: { "1 Kg": 38, "5 Kg": 180 } },
  { name: "Flattened Rice Poha", brand: "Rice & Staples", price: 48, stock: 75, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 48, "1 Kg": 92 } },
  { name: "Puffed Rice Muri", brand: "Rice & Staples", price: 35, stock: 80, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 35, "1 Kg": 68 } },
  { name: "Wheat Atta", brand: "Flour & Grains", price: 58, stock: 95, unitOptions: ["1 Kg", "5 Kg", "10 Kg"], variantPrices: { "1 Kg": 58, "5 Kg": 280, "10 Kg": 550 } },
  { name: "Maida", brand: "Flour & Grains", price: 48, stock: 84, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 25, "1 Kg": 48 } },
  { name: "Besan", brand: "Flour & Grains", price: 92, stock: 72, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 48, "1 Kg": 92 } },
  { name: "Suji", brand: "Flour & Grains", price: 46, stock: 70, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 24, "1 Kg": 46 } },
  { name: "Rice Flour", brand: "Flour & Grains", price: 55, stock: 55, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 29, "1 Kg": 55 } },
  { name: "Corn Flour", brand: "Flour & Grains", price: 38, stock: 50, unitOptions: ["100 Gram", "500 Gram"], variantPrices: { "100 Gram": 15, "500 Gram": 38 } },
  { name: "Sattu", brand: "Flour & Grains", price: 78, stock: 45, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 40, "1 Kg": 78 } },
  { name: "Dalia", brand: "Flour & Grains", price: 62, stock: 48, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 32, "1 Kg": 62 } },
  { name: "Rolled Oats", brand: "Breakfast & Cereals", price: 165, stock: 42, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 165, "1 Kg": 315 } },
  { name: "Corn Flakes", brand: "Breakfast & Cereals", price: 185, stock: 36, unitOptions: ["1 Box", "2 Boxes"], variantPrices: { "1 Box": 185, "2 Boxes": 360 } },
  { name: "Choco Cereal", brand: "Breakfast & Cereals", price: 210, stock: 30, unitOptions: ["1 Box", "2 Boxes"], variantPrices: { "1 Box": 210, "2 Boxes": 405 } },
  { name: "Muesli", brand: "Breakfast & Cereals", price: 260, stock: 28, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 260, "2 Packs": 505 } },
  { name: "Moong Dal", brand: "Pulses & Dal", price: 128, stock: 82, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 66, "1 Kg": 128 } },
  { name: "Masoor Dal", brand: "Pulses & Dal", price: 112, stock: 86, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 58, "1 Kg": 112 } },
  { name: "Toor Dal", brand: "Pulses & Dal", price: 158, stock: 68, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 82, "1 Kg": 158 } },
  { name: "Chana Dal", brand: "Pulses & Dal", price: 92, stock: 75, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 48, "1 Kg": 92 } },
  { name: "Urad Dal", brand: "Pulses & Dal", price: 145, stock: 52, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 75, "1 Kg": 145 } },
  { name: "Yellow Peas Dal", brand: "Pulses & Dal", price: 76, stock: 58, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 40, "1 Kg": 76 } },
  { name: "Rajma", brand: "Pulses & Dal", price: 152, stock: 44, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 78, "1 Kg": 152 } },
  { name: "Kabuli Chana", brand: "Pulses & Dal", price: 142, stock: 46, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 73, "1 Kg": 142 } },
  { name: "Black Chana", brand: "Pulses & Dal", price: 92, stock: 50, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 48, "1 Kg": 92 } },
  { name: "Soyabean Chunks", brand: "Pulses & Dal", price: 64, stock: 66, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 28, "500 Gram": 64 } },
  { name: "Groundnut", brand: "Nuts & Seeds", price: 135, stock: 60, unitOptions: ["250 Gram", "500 Gram", "1 Kg"], variantPrices: { "250 Gram": 36, "500 Gram": 70, "1 Kg": 135 } },
  { name: "Cashew Nuts", brand: "Nuts & Seeds", price: 960, stock: 32, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 198, "250 Gram": 480, "500 Gram": 960 } },
  { name: "Almonds", brand: "Nuts & Seeds", price: 840, stock: 35, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 172, "250 Gram": 425, "500 Gram": 840 } },
  { name: "Pumpkin Seeds", brand: "Nuts & Seeds", price: 360, stock: 42, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 78, "250 Gram": 185, "500 Gram": 360 } },
  { name: "Sunflower Seeds", brand: "Nuts & Seeds", price: 260, stock: 40, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 58, "250 Gram": 135, "500 Gram": 260 } },
  { name: "Walnuts", brand: "Nuts & Seeds", price: 980, stock: 22, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 205, "250 Gram": 500, "500 Gram": 980 } },
  { name: "Pistachios", brand: "Nuts & Seeds", price: 1120, stock: 18, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 230, "250 Gram": 570, "500 Gram": 1120 } },
  { name: "Fox Nuts Makhana", brand: "Nuts & Seeds", price: 520, stock: 26, unitOptions: ["100 Gram", "250 Gram"], variantPrices: { "100 Gram": 215, "250 Gram": 520 } },
  { name: "Sesame Seeds", brand: "Oils & Spices", price: 180, stock: 42, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 38, "250 Gram": 90, "500 Gram": 180 } },
  { name: "Mustard Seeds", brand: "Oils & Spices", price: 88, stock: 55, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 20, "250 Gram": 45, "500 Gram": 88 } },
  { name: "Coriander Seeds", brand: "Oils & Spices", price: 105, stock: 52, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 24, "250 Gram": 55, "500 Gram": 105 } },
  { name: "Fennel Seeds", brand: "Oils & Spices", price: 165, stock: 44, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 36, "250 Gram": 84, "500 Gram": 165 } },
  { name: "Fenugreek Seeds", brand: "Oils & Spices", price: 95, stock: 48, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 22, "250 Gram": 50, "500 Gram": 95 } },
  { name: "Nigella Seeds Kalonji", brand: "Oils & Spices", price: 220, stock: 36, unitOptions: ["50 Gram", "100 Gram", "250 Gram"], variantPrices: { "50 Gram": 46, "100 Gram": 88, "250 Gram": 220 } },
  { name: "Bay Leaves", brand: "Oils & Spices", price: 45, stock: 40, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 24, "100 Gram": 45 } },
  { name: "Dry Red Chili", brand: "Oils & Spices", price: 210, stock: 38, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 44, "250 Gram": 108, "500 Gram": 210 } },
  { name: "Cardamom", brand: "Oils & Spices", price: 1950, stock: 15, unitOptions: ["25 Gram", "50 Gram", "100 Gram"], variantPrices: { "25 Gram": 500, "50 Gram": 980, "100 Gram": 1950 } },
  { name: "Cloves", brand: "Oils & Spices", price: 920, stock: 18, unitOptions: ["25 Gram", "50 Gram", "100 Gram"], variantPrices: { "25 Gram": 240, "50 Gram": 465, "100 Gram": 920 } },
  { name: "Cinnamon", brand: "Oils & Spices", price: 420, stock: 28, unitOptions: ["50 Gram", "100 Gram", "250 Gram"], variantPrices: { "50 Gram": 88, "100 Gram": 170, "250 Gram": 420 } },
  { name: "Star Anise", brand: "Oils & Spices", price: 680, stock: 18, unitOptions: ["25 Gram", "50 Gram", "100 Gram"], variantPrices: { "25 Gram": 175, "50 Gram": 345, "100 Gram": 680 } },
  { name: "Hing Asafoetida", brand: "Oils & Spices", price: 145, stock: 34, unitOptions: ["10 Gram", "25 Gram", "50 Gram"], variantPrices: { "10 Gram": 35, "25 Gram": 75, "50 Gram": 145 } },
  { name: "Kitchen King Masala", brand: "Oils & Spices", price: 72, stock: 45, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 38, "100 Gram": 72 } },
  { name: "Meat Masala", brand: "Oils & Spices", price: 75, stock: 50, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 40, "100 Gram": 75 } },
  { name: "Fish Curry Masala", brand: "Oils & Spices", price: 68, stock: 46, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 36, "100 Gram": 68 } },
  { name: "Chicken Masala", brand: "Oils & Spices", price: 78, stock: 48, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 42, "100 Gram": 78 } },
  { name: "Biryani Masala", brand: "Oils & Spices", price: 86, stock: 42, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 45, "100 Gram": 86 } },
  { name: "Paneer Masala", brand: "Oils & Spices", price: 76, stock: 36, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 40, "100 Gram": 76 } },
  { name: "Chaat Masala", brand: "Oils & Spices", price: 62, stock: 44, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 33, "100 Gram": 62 } },
  { name: "Black Salt", brand: "Oils & Spices", price: 42, stock: 52, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 18, "500 Gram": 42 } },
  { name: "Rock Salt", brand: "Oils & Spices", price: 46, stock: 50, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 20, "500 Gram": 46 } },
  { name: "Jaggery", brand: "Sugar & Sweeteners", price: 92, stock: 55, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 48, "1 Kg": 92 } },
  { name: "Sugar Cubes", brand: "Sugar & Sweeteners", price: 78, stock: 30, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 78, "1 Kg": 150 } },
  { name: "Mishri", brand: "Sugar & Sweeteners", price: 88, stock: 32, unitOptions: ["250 Gram", "500 Gram"], variantPrices: { "250 Gram": 45, "500 Gram": 88 } },
  { name: "Honey", brand: "Sugar & Sweeteners", price: 165, stock: 28, unitOptions: ["250 Gram", "500 Gram"], variantPrices: { "250 Gram": 165, "500 Gram": 310 } },
  { name: "Schezwan Sauce", brand: "Sauces & Spreads", price: 115, stock: 45, unitOptions: ["250 Gram", "500 Gram"], variantPrices: { "250 Gram": 65, "500 Gram": 115 } },
  { name: "Chili Sauce", brand: "Sauces & Spreads", price: 92, stock: 38, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 45, "500 Gram": 92 } },
  { name: "Soy Sauce", brand: "Sauces & Spreads", price: 85, stock: 36, unitOptions: ["200 ml", "700 ml"], variantPrices: { "200 ml": 85, "700 ml": 240 } },
  { name: "Vinegar", brand: "Sauces & Spreads", price: 48, stock: 40, unitOptions: ["200 ml", "700 ml"], variantPrices: { "200 ml": 48, "700 ml": 135 } },
  { name: "Green Chili Sauce", brand: "Sauces & Spreads", price: 88, stock: 34, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 42, "500 Gram": 88 } },
  { name: "Mayonnaise", brand: "Sauces & Spreads", price: 145, stock: 28, unitOptions: ["250 Gram", "500 Gram"], variantPrices: { "250 Gram": 78, "500 Gram": 145 } },
  { name: "Mixed Pickle", brand: "Sauces & Spreads", price: 135, stock: 35, unitOptions: ["400 Gram", "1 Kg"], variantPrices: { "400 Gram": 135, "1 Kg": 310 } },
  { name: "Garlic Pickle", brand: "Sauces & Spreads", price: 128, stock: 34, unitOptions: ["400 Gram", "1 Kg"], variantPrices: { "400 Gram": 128, "1 Kg": 295 } },
  { name: "Lime Pickle", brand: "Sauces & Spreads", price: 125, stock: 32, unitOptions: ["400 Gram", "1 Kg"], variantPrices: { "400 Gram": 125, "1 Kg": 290 } },
  { name: "Peanut Butter", brand: "Sauces & Spreads", price: 210, stock: 24, unitOptions: ["340 Gram", "1 Kg"], variantPrices: { "340 Gram": 210, "1 Kg": 560 } },
  { name: "Jam", brand: "Sauces & Spreads", price: 145, stock: 30, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 145, "1 Kg": 280 } },
  { name: "Ghee", brand: "Dairy & Bakery", price: 620, stock: 30, unitOptions: ["500 ml", "1 Liter"], variantPrices: { "500 ml": 320, "1 Liter": 620 } },
  { name: "Butter", brand: "Dairy & Bakery", price: 58, stock: 42, unitOptions: ["100 Gram", "500 Gram"], variantPrices: { "100 Gram": 58, "500 Gram": 280 } },
  { name: "Cheese Slices", brand: "Dairy & Bakery", price: 145, stock: 28, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 145, "2 Packs": 280 } },
  { name: "Processed Cheese", brand: "Dairy & Bakery", price: 135, stock: 30, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 135, "500 Gram": 320 } },
  { name: "Paneer", brand: "Dairy & Bakery", price: 92, stock: 36, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 92, "500 Gram": 220 } },
  { name: "Bread", brand: "Dairy & Bakery", price: 45, stock: 60, unitOptions: ["1 Loaf", "2 Loaves"], variantPrices: { "1 Loaf": 45, "2 Loaves": 88 } },
  { name: "Brown Bread", brand: "Dairy & Bakery", price: 55, stock: 42, unitOptions: ["1 Loaf", "2 Loaves"], variantPrices: { "1 Loaf": 55, "2 Loaves": 108 } },
  { name: "Rusk", brand: "Dairy & Bakery", price: 55, stock: 55, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 55, "2 Packs": 105 } },
  { name: "Khari Biscuit", brand: "Dairy & Bakery", price: 65, stock: 45, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 65, "2 Packs": 125 } },
  { name: "Cake Rusk", brand: "Dairy & Bakery", price: 75, stock: 38, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 75, "2 Packs": 145 } },
  { name: "Marie Biscuit", brand: "Biscuits & Snacks", price: 35, stock: 90, unitOptions: ["1 Pack", "4 Packs"], variantPrices: { "1 Pack": 35, "4 Packs": 135 } },
  { name: "Glucose Biscuit", brand: "Biscuits & Snacks", price: 10, stock: 160, unitOptions: ["1 Pack", "10 Packs"], variantPrices: { "1 Pack": 10, "10 Packs": 95 } },
  { name: "Cream Biscuit", brand: "Biscuits & Snacks", price: 35, stock: 110, unitOptions: ["1 Pack", "4 Packs"], variantPrices: { "1 Pack": 35, "4 Packs": 135 } },
  { name: "Digestive Biscuit", brand: "Biscuits & Snacks", price: 60, stock: 72, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 60, "2 Packs": 115 } },
  { name: "Salted Crackers", brand: "Biscuits & Snacks", price: 45, stock: 65, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 45, "3 Packs": 130 } },
  { name: "Rice Crisps", brand: "Biscuits & Snacks", price: 20, stock: 150, unitOptions: ["1 Pack", "5 Packs"], variantPrices: { "1 Pack": 20, "5 Packs": 95 } },
  { name: "Masala Peanuts", brand: "Biscuits & Snacks", price: 65, stock: 50, unitOptions: ["100 Gram", "250 Gram"], variantPrices: { "100 Gram": 30, "250 Gram": 65 } },
  { name: "Namkeen Mixture", brand: "Biscuits & Snacks", price: 55, stock: 82, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 55, "500 Gram": 130 } },
  { name: "Chanachur", brand: "Biscuits & Snacks", price: 48, stock: 88, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 48, "500 Gram": 115 } },
  { name: "Bhujia", brand: "Biscuits & Snacks", price: 58, stock: 80, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 58, "500 Gram": 138 } },
  { name: "Nimki", brand: "Biscuits & Snacks", price: 50, stock: 74, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 50, "500 Gram": 120 } },
  { name: "Sev", brand: "Biscuits & Snacks", price: 52, stock: 72, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 52, "500 Gram": 125 } },
  { name: "Papad", brand: "Biscuits & Snacks", price: 60, stock: 55, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 60, "500 Gram": 145 } },
  { name: "Fryums", brand: "Biscuits & Snacks", price: 45, stock: 62, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 45, "500 Gram": 108 } },
  { name: "Popcorn Kernels", brand: "Biscuits & Snacks", price: 75, stock: 44, unitOptions: ["250 Gram", "500 Gram"], variantPrices: { "250 Gram": 40, "500 Gram": 75 } },
  { name: "Instant Vermicelli", brand: "Instant Foods", price: 35, stock: 80, unitOptions: ["1 Pack", "4 Packs"], variantPrices: { "1 Pack": 35, "4 Packs": 132 } },
  { name: "Hakka Noodles", brand: "Instant Foods", price: 55, stock: 70, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 55, "3 Packs": 158 } },
  { name: "Ready Poha Mix", brand: "Instant Foods", price: 68, stock: 48, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 68, "3 Packs": 198 } },
  { name: "Upma Mix", brand: "Instant Foods", price: 72, stock: 44, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 72, "3 Packs": 210 } },
  { name: "Idli Mix", brand: "Instant Foods", price: 95, stock: 40, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 95, "2 Packs": 185 } },
  { name: "Dosa Mix", brand: "Instant Foods", price: 105, stock: 36, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 105, "2 Packs": 205 } },
  { name: "Gulab Jamun Mix", brand: "Instant Foods", price: 110, stock: 34, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 110, "2 Packs": 215 } },
  { name: "Custard Powder", brand: "Instant Foods", price: 42, stock: 46, unitOptions: ["100 Gram", "500 Gram"], variantPrices: { "100 Gram": 42, "500 Gram": 195 } },
  { name: "Baking Powder", brand: "Instant Foods", price: 35, stock: 42, unitOptions: ["100 Gram", "500 Gram"], variantPrices: { "100 Gram": 35, "500 Gram": 160 } },
  { name: "Baking Soda", brand: "Instant Foods", price: 28, stock: 45, unitOptions: ["100 Gram", "500 Gram"], variantPrices: { "100 Gram": 28, "500 Gram": 130 } },
  { name: "Yeast", brand: "Instant Foods", price: 45, stock: 30, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 45, "100 Gram": 85 } },
  { name: "Cocoa Powder", brand: "Instant Foods", price: 130, stock: 28, unitOptions: ["100 Gram", "250 Gram"], variantPrices: { "100 Gram": 55, "250 Gram": 130 } },
  { name: "Vanilla Essence", brand: "Instant Foods", price: 42, stock: 36, unitOptions: ["20 ml", "100 ml"], variantPrices: { "20 ml": 42, "100 ml": 180 } },
  { name: "Frozen Paratha", brand: "Frozen Foods", price: 135, stock: 32, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 135, "2 Packs": 260 } },
  { name: "Frozen Roti", brand: "Frozen Foods", price: 120, stock: 30, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 120, "2 Packs": 230 } },
  { name: "Frozen Samosa", brand: "Frozen Foods", price: 150, stock: 28, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 150, "2 Packs": 290 } },
  { name: "Frozen Spring Roll", brand: "Frozen Foods", price: 175, stock: 24, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 175, "2 Packs": 340 } },
  { name: "Frozen Chicken Nuggets", brand: "Frozen Foods", price: 260, stock: 22, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 260, "2 Packs": 505 } },
  { name: "Frozen Fish Finger", brand: "Frozen Foods", price: 285, stock: 20, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 285, "2 Packs": 555 } },
  { name: "Chicken Eggs Dozen", brand: "Meat & Seafood", price: 84, stock: 65, unitOptions: ["6 Pieces", "12 Pieces", "30 Pieces"], variantPrices: { "6 Pieces": 42, "12 Pieces": 84, "30 Pieces": 210 } },
  { name: "Chicken Curry Cut", brand: "Meat & Seafood", price: 240, stock: 24, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 120, "1 Kg": 240 } },
  { name: "Chicken Breast Boneless", brand: "Meat & Seafood", price: 380, stock: 18, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 195, "1 Kg": 380 } },
  { name: "Chicken Keema", brand: "Meat & Seafood", price: 340, stock: 16, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 175, "1 Kg": 340 } },
  { name: "Rohu Fish Cut", brand: "Meat & Seafood", price: 260, stock: 20, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 135, "1 Kg": 260 } },
  { name: "Katla Fish Cut", brand: "Meat & Seafood", price: 280, stock: 20, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 145, "1 Kg": 280 } },
  { name: "Prawn Medium", brand: "Meat & Seafood", price: 520, stock: 14, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 270, "1 Kg": 520 } },
  { name: "Fish Egg Roe", brand: "Meat & Seafood", price: 420, stock: 10, unitOptions: ["250 Gram", "500 Gram"], variantPrices: { "250 Gram": 215, "500 Gram": 420 } },
  { name: "Laundry Detergent Bar", brand: "Household", price: 25, stock: 120, unitOptions: ["1 Piece", "4 Pieces"], variantPrices: { "1 Piece": 25, "4 Pieces": 95 } },
  { name: "Fabric Softener", brand: "Household", price: 170, stock: 34, unitOptions: ["500 ml", "1 Liter"], variantPrices: { "500 ml": 170, "1 Liter": 325 } },
  { name: "Floor Cleaner", brand: "Household", price: 145, stock: 45, unitOptions: ["500 ml", "1 Liter"], variantPrices: { "500 ml": 75, "1 Liter": 145 } },
  { name: "Toilet Cleaner", brand: "Household", price: 105, stock: 50, unitOptions: ["500 ml", "1 Liter"], variantPrices: { "500 ml": 105, "1 Liter": 200 } },
  { name: "Bathroom Cleaner", brand: "Household", price: 118, stock: 42, unitOptions: ["500 ml", "1 Liter"], variantPrices: { "500 ml": 118, "1 Liter": 225 } },
  { name: "Glass Cleaner", brand: "Household", price: 110, stock: 36, unitOptions: ["500 ml", "1 Liter"], variantPrices: { "500 ml": 110, "1 Liter": 210 } },
  { name: "Phenyl", brand: "Household", price: 92, stock: 55, unitOptions: ["1 Liter", "5 Liter"], variantPrices: { "1 Liter": 92, "5 Liter": 430 } },
  { name: "Bleaching Powder", brand: "Household", price: 48, stock: 48, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 25, "1 Kg": 48 } },
  { name: "Dishwash Bar", brand: "Household", price: 20, stock: 130, unitOptions: ["1 Piece", "4 Pieces"], variantPrices: { "1 Piece": 20, "4 Pieces": 76 } },
  { name: "Scrub Pad", brand: "Household", price: 18, stock: 90, unitOptions: ["1 Piece", "6 Pieces"], variantPrices: { "1 Piece": 18, "6 Pieces": 100 } },
  { name: "Steel Scrubber", brand: "Household", price: 15, stock: 100, unitOptions: ["1 Piece", "6 Pieces"], variantPrices: { "1 Piece": 15, "6 Pieces": 82 } },
  { name: "Cleaning Sponge", brand: "Household", price: 25, stock: 80, unitOptions: ["1 Piece", "4 Pieces"], variantPrices: { "1 Piece": 25, "4 Pieces": 95 } },
  { name: "Broom", brand: "Household", price: 95, stock: 35, unitOptions: ["1 Piece", "2 Pieces"], variantPrices: { "1 Piece": 95, "2 Pieces": 180 } },
  { name: "Mop Refill", brand: "Household", price: 115, stock: 28, unitOptions: ["1 Piece", "2 Pieces"], variantPrices: { "1 Piece": 115, "2 Pieces": 220 } },
  { name: "Microfiber Cloth", brand: "Household", price: 45, stock: 60, unitOptions: ["1 Piece", "4 Pieces"], variantPrices: { "1 Piece": 45, "4 Pieces": 170 } },
  { name: "Aluminium Foil", brand: "Household", price: 85, stock: 42, unitOptions: ["1 Roll", "2 Rolls"], variantPrices: { "1 Roll": 85, "2 Rolls": 165 } },
  { name: "Cling Film", brand: "Household", price: 90, stock: 30, unitOptions: ["1 Roll", "2 Rolls"], variantPrices: { "1 Roll": 90, "2 Rolls": 175 } },
  { name: "Tissue Roll", brand: "Household", price: 35, stock: 95, unitOptions: ["1 Roll", "6 Rolls"], variantPrices: { "1 Roll": 35, "6 Rolls": 200 } },
  { name: "Paper Napkins", brand: "Household", price: 65, stock: 70, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 65, "3 Packs": 188 } },
  { name: "Matchbox", brand: "Household", price: 10, stock: 200, unitOptions: ["1 Box", "10 Boxes"], variantPrices: { "1 Box": 10, "10 Boxes": 95 } },
  { name: "Agarbatti", brand: "Puja Essentials", price: 35, stock: 110, unitOptions: ["1 Pack", "4 Packs"], variantPrices: { "1 Pack": 35, "4 Packs": 130 } },
  { name: "Dhoop Sticks", brand: "Puja Essentials", price: 45, stock: 85, unitOptions: ["1 Pack", "4 Packs"], variantPrices: { "1 Pack": 45, "4 Packs": 170 } },
  { name: "Camphor", brand: "Puja Essentials", price: 38, stock: 75, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 38, "3 Packs": 108 } },
  { name: "Cotton Wicks", brand: "Puja Essentials", price: 25, stock: 90, unitOptions: ["1 Pack", "4 Packs"], variantPrices: { "1 Pack": 25, "4 Packs": 95 } },
  { name: "Puja Oil", brand: "Puja Essentials", price: 78, stock: 45, unitOptions: ["500 ml", "1 Liter"], variantPrices: { "500 ml": 40, "1 Liter": 78 } },
  { name: "Sindoor", brand: "Puja Essentials", price: 20, stock: 70, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 20, "3 Packs": 55 } },
  { name: "Ganga Jal Bottle", brand: "Puja Essentials", price: 35, stock: 50, unitOptions: ["1 Bottle", "2 Bottles"], variantPrices: { "1 Bottle": 35, "2 Bottles": 68 } },
  { name: "Toothbrush", brand: "Personal Care", price: 35, stock: 90, unitOptions: ["1 Piece", "4 Pieces"], variantPrices: { "1 Piece": 35, "4 Pieces": 130 } },
  { name: "Mouthwash", brand: "Personal Care", price: 165, stock: 35, unitOptions: ["250 ml", "500 ml"], variantPrices: { "250 ml": 90, "500 ml": 165 } },
  { name: "Face Wash", brand: "Personal Care", price: 145, stock: 42, unitOptions: ["100 Gram", "200 Gram"], variantPrices: { "100 Gram": 145, "200 Gram": 280 } },
  { name: "Body Lotion", brand: "Personal Care", price: 180, stock: 32, unitOptions: ["200 ml", "400 ml"], variantPrices: { "200 ml": 180, "400 ml": 345 } },
  { name: "Talcum Powder", brand: "Personal Care", price: 95, stock: 55, unitOptions: ["100 Gram", "400 Gram"], variantPrices: { "100 Gram": 45, "400 Gram": 95 } },
  { name: "Handwash", brand: "Personal Care", price: 105, stock: 48, unitOptions: ["250 ml", "750 ml"], variantPrices: { "250 ml": 55, "750 ml": 105 } },
  { name: "Sanitizer", brand: "Personal Care", price: 75, stock: 60, unitOptions: ["100 ml", "500 ml"], variantPrices: { "100 ml": 30, "500 ml": 75 } },
  { name: "Deodorant", brand: "Personal Care", price: 210, stock: 34, unitOptions: ["1 Bottle", "2 Bottles"], variantPrices: { "1 Bottle": 210, "2 Bottles": 405 } },
  { name: "Shaving Cream", brand: "Personal Care", price: 95, stock: 38, unitOptions: ["1 Tube", "2 Tubes"], variantPrices: { "1 Tube": 95, "2 Tubes": 185 } },
  { name: "Razor", brand: "Personal Care", price: 60, stock: 52, unitOptions: ["1 Piece", "4 Pieces"], variantPrices: { "1 Piece": 60, "4 Pieces": 225 } },
  { name: "Sanitary Pads", brand: "Personal Care", price: 95, stock: 60, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 95, "3 Packs": 275 } },
  { name: "Cotton Buds", brand: "Personal Care", price: 45, stock: 65, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 45, "3 Packs": 128 } },
  { name: "Petroleum Jelly", brand: "Personal Care", price: 70, stock: 40, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 38, "100 Gram": 70 } },
  { name: "Baby Soap", brand: "Baby Care", price: 58, stock: 50, unitOptions: ["1 Piece", "4 Pieces"], variantPrices: { "1 Piece": 58, "4 Pieces": 220 } },
  { name: "Baby Shampoo", brand: "Baby Care", price: 165, stock: 32, unitOptions: ["100 ml", "200 ml"], variantPrices: { "100 ml": 90, "200 ml": 165 } },
  { name: "Baby Powder", brand: "Baby Care", price: 135, stock: 36, unitOptions: ["100 Gram", "400 Gram"], variantPrices: { "100 Gram": 55, "400 Gram": 135 } },
  { name: "Baby Oil", brand: "Baby Care", price: 160, stock: 34, unitOptions: ["100 ml", "200 ml"], variantPrices: { "100 ml": 85, "200 ml": 160 } },
  { name: "Baby Cream", brand: "Baby Care", price: 115, stock: 30, unitOptions: ["50 Gram", "100 Gram"], variantPrices: { "50 Gram": 62, "100 Gram": 115 } },
  { name: "Baby Feeding Bottle", brand: "Baby Care", price: 155, stock: 22, unitOptions: ["1 Piece", "2 Pieces"], variantPrices: { "1 Piece": 155, "2 Pieces": 300 } },
  { name: "Baby Cereal", brand: "Baby Care", price: 235, stock: 24, unitOptions: ["300 Gram", "1 Kg"], variantPrices: { "300 Gram": 235, "1 Kg": 740 } },
  { name: "Dog Food", brand: "Pet Care", price: 220, stock: 28, unitOptions: ["1 Kg", "3 Kg"], variantPrices: { "1 Kg": 220, "3 Kg": 630 } },
  { name: "Cat Food", brand: "Pet Care", price: 195, stock: 24, unitOptions: ["1 Kg", "3 Kg"], variantPrices: { "1 Kg": 195, "3 Kg": 560 } },
  { name: "Pet Treats", brand: "Pet Care", price: 95, stock: 30, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 95, "3 Packs": 275 } },
  { name: "Cat Litter", brand: "Pet Care", price: 320, stock: 18, unitOptions: ["5 Kg", "10 Kg"], variantPrices: { "5 Kg": 320, "10 Kg": 610 } },
  { name: "Dog Biscuits", brand: "Pet Care", price: 85, stock: 35, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 85, "3 Packs": 245 } },
  { name: "Notebook", brand: "Stationery", price: 45, stock: 80, unitOptions: ["1 Piece", "6 Pieces"], variantPrices: { "1 Piece": 45, "6 Pieces": 255 } },
  { name: "Ball Pen", brand: "Stationery", price: 10, stock: 180, unitOptions: ["1 Piece", "10 Pieces"], variantPrices: { "1 Piece": 10, "10 Pieces": 95 } },
  { name: "Pencil", brand: "Stationery", price: 6, stock: 200, unitOptions: ["1 Piece", "10 Pieces"], variantPrices: { "1 Piece": 6, "10 Pieces": 55 } },
  { name: "Eraser", brand: "Stationery", price: 5, stock: 160, unitOptions: ["1 Piece", "10 Pieces"], variantPrices: { "1 Piece": 5, "10 Pieces": 45 } },
  { name: "Sharpener", brand: "Stationery", price: 8, stock: 140, unitOptions: ["1 Piece", "10 Pieces"], variantPrices: { "1 Piece": 8, "10 Pieces": 75 } },
  { name: "Glue Stick", brand: "Stationery", price: 25, stock: 70, unitOptions: ["1 Piece", "4 Pieces"], variantPrices: { "1 Piece": 25, "4 Pieces": 95 } },
  { name: "Fevicol", brand: "Stationery", price: 35, stock: 60, unitOptions: ["50 Gram", "200 Gram"], variantPrices: { "50 Gram": 35, "200 Gram": 120 } },
  { name: "A4 Paper", brand: "Stationery", price: 220, stock: 35, unitOptions: ["1 Ream", "2 Reams"], variantPrices: { "1 Ream": 220, "2 Reams": 430 } },
  { name: "Envelope", brand: "Stationery", price: 2, stock: 300, unitOptions: ["1 Piece", "50 Pieces"], variantPrices: { "1 Piece": 2, "50 Pieces": 90 } },
  { name: "Cigarette Gold Flake Kings", brand: "Tobacco", price: 180, stock: 40, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 180, "2 Packs": 360 } },
  { name: "Cigarette Gold Flake Lights", brand: "Tobacco", price: 175, stock: 38, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 175, "2 Packs": 350 } },
  { name: "Cigarette Classic Regular", brand: "Tobacco", price: 195, stock: 32, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 195, "2 Packs": 390 } },
  { name: "Cigarette Classic Milds", brand: "Tobacco", price: 200, stock: 30, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 200, "2 Packs": 400 } },
  { name: "Cigarette Navy Cut", brand: "Tobacco", price: 170, stock: 36, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 170, "2 Packs": 340 } },
  { name: "Cigarette Wills Filter", brand: "Tobacco", price: 160, stock: 35, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 160, "2 Packs": 320 } },
  { name: "Cigarette Flake Mint", brand: "Tobacco", price: 150, stock: 28, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 150, "2 Packs": 300 } },
  { name: "Cigarette Indie Mint", brand: "Tobacco", price: 120, stock: 25, unitOptions: ["1 Pack", "2 Packs"], variantPrices: { "1 Pack": 120, "2 Packs": 240 } },
  { name: "Bidi Bundle", brand: "Tobacco", price: 25, stock: 80, unitOptions: ["1 Bundle", "10 Bundles"], variantPrices: { "1 Bundle": 25, "10 Bundles": 240 } },
  { name: "Loose Tobacco Pouch", brand: "Tobacco", price: 45, stock: 50, unitOptions: ["1 Pouch", "5 Pouches"], variantPrices: { "1 Pouch": 45, "5 Pouches": 220 } },
  { name: "Khaini Pouch", brand: "Tobacco", price: 10, stock: 150, unitOptions: ["1 Pouch", "10 Pouches"], variantPrices: { "1 Pouch": 10, "10 Pouches": 95 } },
  { name: "Zarda Pouch", brand: "Tobacco", price: 20, stock: 90, unitOptions: ["1 Pouch", "10 Pouches"], variantPrices: { "1 Pouch": 20, "10 Pouches": 190 } },
  { name: "Smoking Rolling Paper", brand: "Tobacco", price: 35, stock: 40, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 35, "3 Packs": 100 } },
  { name: "Turmeric Whole", brand: "Oils & Spices", price: 160, stock: 36, unitOptions: ["250 Gram", "500 Gram"], variantPrices: { "250 Gram": 82, "500 Gram": 160 } },
  { name: "Dried Ginger", brand: "Oils & Spices", price: 260, stock: 28, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 55, "250 Gram": 135, "500 Gram": 260 } },
  { name: "White Pepper", brand: "Oils & Spices", price: 620, stock: 20, unitOptions: ["50 Gram", "100 Gram", "250 Gram"], variantPrices: { "50 Gram": 128, "100 Gram": 250, "250 Gram": 620 } },
  { name: "Mace Javitri", brand: "Oils & Spices", price: 1180, stock: 14, unitOptions: ["25 Gram", "50 Gram", "100 Gram"], variantPrices: { "25 Gram": 300, "50 Gram": 590, "100 Gram": 1180 } },
  { name: "Nutmeg Jaiphal", brand: "Oils & Spices", price: 540, stock: 22, unitOptions: ["50 Gram", "100 Gram", "250 Gram"], variantPrices: { "50 Gram": 110, "100 Gram": 220, "250 Gram": 540 } },
  { name: "Poppy Seeds", brand: "Nuts & Seeds", price: 980, stock: 18, unitOptions: ["50 Gram", "100 Gram", "250 Gram"], variantPrices: { "50 Gram": 198, "100 Gram": 390, "250 Gram": 980 } },
  { name: "Chia Seeds", brand: "Nuts & Seeds", price: 360, stock: 26, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 78, "250 Gram": 185, "500 Gram": 360 } },
  { name: "Flax Seeds", brand: "Nuts & Seeds", price: 180, stock: 34, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 40, "250 Gram": 92, "500 Gram": 180 } },
  { name: "Mixed Seed Kernels", brand: "Nuts & Seeds", price: 420, stock: 22, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 88, "250 Gram": 215, "500 Gram": 420 } },
  { name: "Char Magaz Seeds", brand: "Nuts & Seeds", price: 460, stock: 20, unitOptions: ["100 Gram", "250 Gram", "500 Gram"], variantPrices: { "100 Gram": 95, "250 Gram": 235, "500 Gram": 460 } },
  { name: "Refined Soybean Oil", brand: "Oils & Spices", price: 138, stock: 58, unitOptions: ["1 Liter", "5 Liter"], variantPrices: { "1 Liter": 138, "5 Liter": 665 } },
  { name: "Rice Bran Oil", brand: "Oils & Spices", price: 155, stock: 44, unitOptions: ["1 Liter", "5 Liter"], variantPrices: { "1 Liter": 155, "5 Liter": 750 } },
  { name: "Groundnut Oil", brand: "Oils & Spices", price: 210, stock: 30, unitOptions: ["1 Liter", "5 Liter"], variantPrices: { "1 Liter": 210, "5 Liter": 1020 } },
  { name: "Coconut Oil", brand: "Oils & Spices", price: 165, stock: 38, unitOptions: ["500 ml", "1 Liter"], variantPrices: { "500 ml": 85, "1 Liter": 165 } },
  { name: "Sesame Oil", brand: "Oils & Spices", price: 240, stock: 26, unitOptions: ["500 ml", "1 Liter"], variantPrices: { "500 ml": 125, "1 Liter": 240 } },
  { name: "Cow Ghee Pouch", brand: "Dairy & Bakery", price: 165, stock: 38, unitOptions: ["200 ml", "500 ml"], variantPrices: { "200 ml": 165, "500 ml": 395 } },
  { name: "Cooking Butter Unsalted", brand: "Dairy & Bakery", price: 62, stock: 36, unitOptions: ["100 Gram", "500 Gram"], variantPrices: { "100 Gram": 62, "500 Gram": 295 } },
  { name: "Malai Paneer", brand: "Dairy & Bakery", price: 110, stock: 28, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 110, "500 Gram": 265 } },
  { name: "Pizza Cheese", brand: "Dairy & Bakery", price: 175, stock: 26, unitOptions: ["200 Gram", "500 Gram"], variantPrices: { "200 Gram": 175, "500 Gram": 420 } },
  { name: "Burger Bun", brand: "Dairy & Bakery", price: 42, stock: 44, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 42, "3 Packs": 120 } },
  { name: "Coconut Cookies", brand: "Biscuits & Snacks", price: 55, stock: 58, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 55, "3 Packs": 158 } },
  { name: "Jeera Cookies", brand: "Biscuits & Snacks", price: 50, stock: 62, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 50, "3 Packs": 145 } },
  { name: "Elaichi Cookies", brand: "Biscuits & Snacks", price: 58, stock: 50, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 58, "3 Packs": 168 } },
  { name: "Chocolate Wafer", brand: "Biscuits & Snacks", price: 30, stock: 90, unitOptions: ["1 Pack", "6 Packs"], variantPrices: { "1 Pack": 30, "6 Packs": 172 } },
  { name: "Cream Roll", brand: "Biscuits & Snacks", price: 25, stock: 85, unitOptions: ["1 Piece", "6 Pieces"], variantPrices: { "1 Piece": 25, "6 Pieces": 140 } },
  { name: "Chicken Sausage", brand: "Meat & Seafood", price: 210, stock: 18, unitOptions: ["250 Gram", "500 Gram"], variantPrices: { "250 Gram": 108, "500 Gram": 210 } },
  { name: "Fish Fillet", brand: "Meat & Seafood", price: 360, stock: 16, unitOptions: ["500 Gram", "1 Kg"], variantPrices: { "500 Gram": 185, "1 Kg": 360 } },
  { name: "Dry Fish Shutki", brand: "Meat & Seafood", price: 420, stock: 12, unitOptions: ["250 Gram", "500 Gram"], variantPrices: { "250 Gram": 215, "500 Gram": 420 } },
  { name: "Egg Tray", brand: "Meat & Seafood", price: 210, stock: 24, unitOptions: ["30 Pieces", "60 Pieces"], variantPrices: { "30 Pieces": 210, "60 Pieces": 420 } },
  { name: "Mosquito Coil", brand: "Household", price: 45, stock: 90, unitOptions: ["1 Pack", "4 Packs"], variantPrices: { "1 Pack": 45, "4 Packs": 170 } },
  { name: "Mosquito Liquid Refill", brand: "Household", price: 85, stock: 65, unitOptions: ["1 Refill", "3 Refills"], variantPrices: { "1 Refill": 85, "3 Refills": 245 } },
  { name: "Insect Killer Spray", brand: "Household", price: 210, stock: 30, unitOptions: ["1 Bottle", "2 Bottles"], variantPrices: { "1 Bottle": 210, "2 Bottles": 405 } },
  { name: "Shoe Polish", brand: "Household", price: 55, stock: 38, unitOptions: ["1 Tin", "2 Tins"], variantPrices: { "1 Tin": 55, "2 Tins": 105 } },
  { name: "Shoe Brush", brand: "Household", price: 45, stock: 32, unitOptions: ["1 Piece", "2 Pieces"], variantPrices: { "1 Piece": 45, "2 Pieces": 85 } },
  { name: "Room Freshener", brand: "Household", price: 160, stock: 36, unitOptions: ["1 Bottle", "2 Bottles"], variantPrices: { "1 Bottle": 160, "2 Bottles": 310 } },
  { name: "Air Freshener Blocks", brand: "Household", price: 75, stock: 42, unitOptions: ["1 Pack", "3 Packs"], variantPrices: { "1 Pack": 75, "3 Packs": 215 } },
  { name: "Toilet Brush", brand: "Household", price: 85, stock: 28, unitOptions: ["1 Piece", "2 Pieces"], variantPrices: { "1 Piece": 85, "2 Pieces": 160 } }
];

const additionalProducts: Product[] = additionalProductSeeds.map((item, index) => ({
  id: `p-${200 + index}`,
  name: item.name,
  category: item.brand === "Personal Care" || item.brand === "Baby Care" ? "cosmetics" : item.brand === "Stationery" ? "books" : "grocery",
  price: item.price,
  image_url: PRODUCT_IMAGE_PLACEHOLDER,
  description: `${item.name} available from Tapas Grocery Store for local delivery in Hatimuri.`,
  stock: item.stock,
  brand: item.brand,
  dietary: item.dietary ?? [],
  unitType: "package",
  unitOptions: item.unitOptions ?? ["1 Pack", "2 Packs"],
  variantPrices: item.variantPrices ?? { "1 Pack": item.price, "2 Packs": item.price * 2 },
  reviews: []
}));

export const initialProducts: Product[] = [...coreProducts, ...additionalProducts].map((product) => ({
  ...product,
  image_url: getProductPhoto(product)
}));

function getProductPhoto(product: Product) {
  const slug = slugifyProductImage(product.name);
  return `/product-photos/${slug}.jpg`;
}

function slugifyProductImage(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export const initialOrders: Order[] = [
  {
    order_id: "ORD-2401",
    customer_name: "Mita Roy",
    customer_phone: "9876543210",
    delivery_address: {
      id: "addr-mita",
      label: "Home",
      receiverName: "Mita Roy",
      phone: "9876543210",
      line1: "12 Station Road",
      line2: "Flat 2B",
      city: "Kolkata",
      state: "West Bengal",
      pincode: "700001",
      landmark: "Near market gate",
      distanceKm: 0.8,
      latitude: 22.5744,
      longitude: 88.3629
    },
    items_ordered: "Mustard Oil (1 Liter) x 1, Turmeric Powder (100 Gram) x 1, Salt (1 Kg) x 1",
    total_amount: 212,
    subtotal: 212,
    discount_amount: 0,
    payment_method: "UPI",
    payment_status: "Paid",
    delivery_fee: 0,
    delivery_distance: 0.8,
    status: "Preparing",
    assigned_agent_id: "agent-1",
    delivery_eta: "25 minutes",
    refund_status: "Not requested",
    invoice_number: "INV-2401",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString()
  },
  {
    order_id: "ORD-2402",
    customer_name: "Rahul Das",
    customer_phone: "9123456780",
    delivery_address: {
      id: "addr-rahul",
      label: "Work",
      receiverName: "Rahul Das",
      phone: "9123456780",
      line1: "48 College Street",
      line2: "Shop floor",
      city: "Kolkata",
      state: "West Bengal",
      pincode: "700073",
      landmark: "Book lane",
      distanceKm: 1.4,
      latitude: 22.5762,
      longitude: 88.3645
    },
    items_ordered: "Instant Noodles (6 Packets) x 1, Soap (4 Pieces) x 1, Toothpaste (1 Tube) x 1",
    total_amount: 340,
    subtotal: 320,
    discount_amount: 0,
    payment_method: "COD",
    payment_status: "Pending",
    delivery_fee: 20,
    delivery_distance: 1.4,
    status: "Pending",
    assigned_agent_id: undefined,
    delivery_eta: "Waiting for owner confirmation",
    refund_status: "Not requested",
    invoice_number: "INV-2402",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString()
  }
];

export const deliveryAgents: DeliveryAgent[] = [
  {
    id: "agent-1",
    name: "Suman Pal",
    phone: "9000011111",
    active: true
  },
  {
    id: "agent-2",
    name: "Arif Khan",
    phone: "9000022222",
    active: true
  }
];

export const promoCodes: PromoCode[] = [
  {
    code: "TAPAS10",
    type: "percentage",
    value: 10,
    minCartTotal: 200,
    description: "10% off orders above ₹200",
    active: true
  },
  {
    code: "LOCAL50",
    type: "flat",
    value: 50,
    minCartTotal: 500,
    description: "₹50 off weekly grocery baskets",
    active: true
  }
];

export const defaultCustomer: CustomerAccount = {
  id: "cus-default",
  name: "Customer",
  phone: "",
  isBlocked: false,
  addresses: [],
  orderIds: [],
  favoriteProductIds: []
};

